### ISSUE TITLE
Postal codes with leading zeros

### ISSUE THREAD

**Issue by Erawaa** [epctex/walmart-scraper#6]
I recently had a problem using postal codes that start with leading zeros. For example, the code 01020 is a valid postal code, yet I can't find a way to specify it to the actor through Apify's API. The problem is that it expects an integer for that field and, as far as I know, integers cannot have leading zeros in JSONs. So those postal codes are effectively impossible to use.

**Comment by tugkan** [comment]
Hey @Erawaa !

Thank you very much for using our actor and letting us know about your problem. You are right. After your inquiry, we depreciated the `postalCode` field and used the `zipCode` instead. This field is a string field so it should work with any input you provide.

We just updated the actor. Please use the latest version for the best experience
I hope this helps
